### ISSUE TITLE
Cant interact with interface

### ISSUE THREAD

**Issue by rek7** [ControlThings-io/ctmodbus#3]
Unfortunately, the tab-completion and terminal interface does not work. The only command that I've gotten to work is exit. If I'm doing something wrong let me know. I am using version 0.5.1 downloaded from pip.

**Comment by meeas** [comment]
Sorry about that, I just noticed this issue.  

I had changed the API in ctui but forgot to have ctmodbus pinned to a specific patch.  I had fixed it in ControlThings Platform but had apparently forgotten to push it to pypi.

I just uploaded 0.5.3 to pypi which re-synced it with ctui's new API, pinned it to a specific version of ctui to prevent future breakage, and added a lot of new valication when connecting to serial devices and ip services.

Enjoy!
